[nosetests]
# Pysh bug, you can't have a $ outside of quotes that isn't followed by {
# without raising an exception.
exclude=test_rogue_dollarsign
